import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProviders } from "@/providers/AuthProviders";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProviders>
          {children}
          <Toaster
            theme="dark"
            richColors
            closeButton
            position="top-right"
            toastOptions={{
              classNames: {
                toast: "bg-[#0f1115] text-[#e6e7ee] border border-[#2a2b31]",
                actionButton: "bg-[#c5161d] hover:bg-[#b21319] text-white",
                cancelButton:
                  "bg-[#1a1b1f] text-[#e6e7ee] border border-[#2a2b31]",
              },
            }}
          />
        </AuthProviders>
      </body>
    </html>
  );
}
